### PR TITLE
Database Updates

### PR DESCRIPTION
**Pull request by BLamy**
@robo50111 Any Reason not to set the files up like this?

### CODE REVIEW

**Comment by lzganec** [comment]
Why would you make it harder to rebuild the database by separating it into several files and removing the full dump? Combined with removing the model (so that anyone can make quick changes if necessary) it takes much more time since you have to write everything down or track the lines you need to copy-paste.

Any advantages this layout offers that I'm missing?

**Comment by BLamy** [comment]
Having a full dump file and multiple separate files just duplicates the same code in multiple files. 

The act of rebuilding the database will be an automated process. See #19. 

This structure optimized for editing by hand. Do we really need a tool to edit .SQL files? Surely editing by hand is fastest.

**Comment by lzganec** [comment]
Editing by hand is hardly the fastest. Opening the model, making desired changes, and exporting the script is much faster (assuming you are doing more than just adding 1 extra column or something minimal like that) and less error-prone than editing by hand. It's also easier since it gives you a nice visual representation.

I agree that it duplicates some of the code, but that's for convenience during the development. You can have a fast rebuild from the full dump, or you can make changes to the model and export just the "create all tables" script followed by hand editing the insert scripts which is useful when the structure of the tables changes more drastically as in case of table merging/separation.

I don't mind if you have your own preferred way of organizing, but I don't see a reason not to have both options available during the development. We can completely organize it with a single option once we've fully decided on the model we are going to use, but since it's still the time where changes are likely to happen on a regular basis I don't see the benefit of it.

**Comment by BLamy** [comment]
I've pushed a new commit overhauling the database.

**Pull request merged**
